version: "3.7"
services:
    web:
        expose:
            - 5000
        env_file:
            - ./.env.prod
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web
