version: "3.7"
services:
    postgres:
        container_name: postgres
        restart: always
        build: ./postgresql
        volumes:
            - url-shortener-db:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    web:
        container_name: url_shortener
        restart: always
        build:
            context: .
            dockerfile: web/Dockerfile
        depends_on:
            - postgres
        volumes: [
            './.git:/home/url_shortener/.git'
        ]


volumes:
    url-shortener-db:
        name: url-shortener-db
